###
GET http://localhost:8080/contacts/bynames2/{{lname}}.{{fname}}

###
GET http://localhost:8080/contacts/bynames/{{lname}}.{{fname}}

###

###
GET http://localhost:8080/contacts/byname/{{name}}

###
GET http://localhost:8080/contacts/bymail/{{email}}
###
GET http://localhost:8080/chins/{{color_pattern}}

###
GET http://localhost:8080/chins/all

###
GET http://localhost:8080/chins/bysex/{{sex}}

###