###
POST http://localhost:8080/samples/add/7/new_sample/cyan

###
GET http://localhost:8080/samples/bycolor/red

###
GET http://localhost:8080/samples/byversion/1

###
GET http://localhost:8080/samples/bysample/sample

###
GET http://localhost:8080/samples/colorbyversion/1

###
GET http://localhost:8080/contacts/bynames2/{{lname}}.{{fname}}

###
GET http://localhost:8080/contacts/bynames/{{lname}}.{{fname}}

###

###
GET http://localhost:8080/contacts/byname/{{name}}

###
GET http://localhost:8080/contacts/bymail/{{email}}
###
GET http://localhost:8080/chins/{{color_pattern}}

###
GET http://localhost:8080/chins/all

###
GET http://localhost:8080/chins/ordered

###
GET http://localhost:8080/chins/bysex/{{sex}}

###
GET http://localhost:8080/chins/listnames
###