###
GET http://localhost:8080/samples/explicit/1

<> 2020-10-27T173422.200.json
<> 2020-10-27T173202.200.json
<> 2020-10-27T172355.500.json

###
GET http://localhost:8080/samples/native/1

<> 2020-10-27T173304.500.json
<> 2020-10-27T173141.500.json
<> 2020-10-27T172653.500.json

###
POST http://localhost:8080/samples/add/7/new_sample/cyan

###
GET http://localhost:8080/samples/bycolor/red

###
GET http://localhost:8080/samples/byversion/1

###
GET http://localhost:8080/samples/bysample/sample

###
GET http://localhost:8080/samples/colorbyversion/1

###
GET http://localhost:8080/contacts/bynames2/{{lname}}.{{fname}}

###
GET http://localhost:8080/contacts/bynames/{{lname}}.{{fname}}

###

###
GET http://localhost:8080/contacts/byname/{{name}}

###
GET http://localhost:8080/contacts/bymail/{{email}}
###
GET http://localhost:8080/chins/{{color_pattern}}

###
GET http://localhost:8080/chins/all

###
GET http://localhost:8080/chins/ordered

###
GET http://localhost:8080/chins/bysex/{{sex}}

###
GET http://localhost:8080/chins/listnames
###
GET http://localhost:8080/chins/dto_by_color/{{color_pattern}}

###
